# _config.yml
title: Syaofox's Blog
email: syaofox@gmail.com
description: >-
  写点啥。
baseurl: "" # 留空，除非你使用项目页面（如 /repo-name/）
url: "" # 留空，GitHub Pages 会自动处理
github_username: syaofox

# 使用 minima 主题，GitHub Pages 默认支持
theme: minima

# 启用高亮
markdown: kramdown
kramdown:
  input: GFM

minima:
  # 将主页布局的标题设置为其他东西，例如：
  home_title: ""
  # 或者你可以添加一行来控制页面标题在 HTML <title> 标签中的显示
  # 这相对复杂，但可以控制浏览器标签页的显示