# _config.yml
title: Syaofox's Blog
email: syaofox@gmail.com
description: >-
  写点啥。
baseurl: "" # 留空，除非你使用项目页面（如 /repo-name/）
url: "" # 留空，GitHub Pages 会自动处理
github_username: syaofox

# 使用 minima 主题，GitHub Pages 默认支持
theme: minima

# 启用高亮
markdown: kramdown
kramdown:
  input: GFM

# 导航栏链接配置
header_pages:
  - categories.html  # <-- 添加分类页面
  - tags.html        # <-- 添加标签页面
  # - index.md       # 首页通常会自动包含，但你也可以显式添加
  # - about.md       # 如果你有关于页面，也可以添加