baseURL = "https://syaofox.github.io/"
DefaultContentLanguage = "zh" # Theme's display language, supports: en, fr, zh, zh-hant
languageCode = "zh-cn"
title = "霜天晓角"
copyright = "Syaofox 2020 copyright."
theme = "diary"
# googleAnalytics = "UA-123-45"


[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "perldoc"
    tabWidth = 4
  # 开启html
  [markup.goldmark]
    [markup.goldmark.renderer]
      # hardWraps = false
      unsafe = true
      # xHTML = true

[params]
subtitle = "心似白云常自在"
enableGitalk = false
enableReadingTime = true
disableToC=false
disableAutoCollapse=false

# Twitter Card and Open Graph settings
enableOpenGraph = false
enableTwitterCards = false
title = "霜天晓角" # will set 'og:site_name'
description = "心似白云常自在"  # will set 'og:description'

[params.gitalk]
  owner = "user"
  repo = "repo name"
  client_id = "your client id"
  client_secret = "your client secret"
[taxonomies]
   tag = "tags"
   category = "categories"

[[menu.main]]
url = "/posts"
name = "归档"
weight = 1

[[menu.main]]
url = "/categories"
name = "分类"
weight = 2
[[menu.main]]
url = "/tags"
name = "标签"
weight = 3

[[menu.main]]
url = "/index.xml"
name = "RSS 订阅"
weight = 4