name: Deploy to GitHub Pages

on:
  issues:
    types: [opened, edited, milestoned, deleted, pinned, unpinned, closed, reopened, labeled, unlabeled]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
      
      - name: Set up Python
        run: uv python install
      
      - name: Install dependencies
        run: uv sync
      
      - name: Generate HTML content
        env:
          GITHUB_TOKEN: ${{ secrets.BLOG_SECRET }}
        run: uv run python main.py
      
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./html
          publish_branch: gh-pages
          force_orphan: true
